### ISSUE TITLE
mp4 validation problem

### ISSUE THREAD

**Issue by sagdelen** [ruiquelhas/houdin#16]
I have tried to validate various mp4 files, got Bad Request error like:

```
{ 
   "statusCode": 400, 
   "error": "Bad Request", 
   "message": "child \"file\" fails because [\"file\" type is unknown]", 
   "validation": { "source": "payload", "keys": [ "file" ] 
}
```

When i try to use it as standalone, i got 
ValidationError: child "file" fails because ["file" type is unknown]

Ftyp information (in Hex) of my sample set are:
1 - [0x00, 0x00, 0x00, 0x14]
2 - [0x00, 0x00, 0x00, 0x18]
3 - [0x00, 0x00, 0x00, 0x1C]
4 - [0x00, 0x00, 0x00, 0x20]

**Comment by ruiquelhas** [comment]
I guess we already went through this, but the issue here is that [file-type](https://github.com/sindresorhus/file-type) is probably not validating the file(s) as `mp4`. I suggest you try it in [isolation](https://github.com/sindresorhus/file-type#nodejs) to make sure, and open an issue there if that is the case.

Also, I'm not sure how to interpret your sample, are those the first 16 bytes of the `Buffer`? Be aware that the validation, in the worst case scenario, probably has to account for the first 8 bytes for `mp4` in order to account for the [different ftyps](http://www.garykessler.net/library/file_sigs.html) (in case you are trying to validate just a chunk).

**Comment by sagdelen** [comment]
I will try [file-type](https://github.com/sindresorhus/file-type) in isolation to make sure the source of the problem.

My sample belongs to 4 different files, each one is copied from the first four elements from their file content which is a [Uint8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array). I changed them to hexadecimal but they are unsigned integers.

**Comment by sagdelen** [comment]
When i use [file-type](https://github.com/sindresorhus/file-type) in isolation, it validates my files except the first one but i could not manage to validate my other files with houdin

**Comment by sagdelen** [comment]
By the way i accidentally open this issue for houdin but i was actually trying to validate files with [henning](https://github.com/ruiquelhas/henning). I am sorry, you can close this one.

**Comment by ruiquelhas** [comment]
What `whitelist` are you using? I've tried to use [file-type](https://github.com/sindresorhus/file-type) with the signatures documented [here](http://www.garykessler.net/library/file_sigs.html) and got the following results.
- `00 00 00 14 66 74 79 70 69 73 6F 6D` is a signature for `mov` or `video/quicktime`
- `00 00 00 18 66 74 79 70 71 74 20 20` is a signature for `mov` or `video/quicktime`
- `00 00 00 18 66 74 79 70 33 67 70 35` is a signature for `mp4` or `video/mp4`
- `00 00 00 18 66 74 79 70 6D 70 34 32` is a signature for `mp4` or `video/mp4`
- `00 00 00 1C 66 74 79 70 4D 53 4E 56 01 29 00 46 4D 53 4E 56 6D 70 34 32` is not recognized

These are also the same results I get with this package or with [henning](https://github.com/ruiquelhas/henning) since the validation logic is basically delegated to [file-type](https://github.com/sindresorhus/file-type).

**Comment by sagdelen** [comment]
I think my mp4 files are the ones among you detected as not recognised thats why they could not pass validation. I found one format that passes validation and i am planning to use that one from my clients.

Thanks for fast response, you helped lot.

**Comment by ruiquelhas** [comment]
I've updated the list above. Only the last one is effectively not recognized. Sorry for the confusion.
